[tool.ruff]
line-length = 100
extend-include = ["*.ipynb"]
target-version = "py311"
select = [
    "ALL", # include all the rules, including new ones
]

ignore = [
    #### specific rules
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "E402",   # false positives for local imports
    "TRY003", # external messages in exceptions are too verbose
    "TD002",
    "TD003",
    "FIX002", # too verbose descriptions of todos
    "PLR0913",  # too many arguments in functions definition
    "ANN204",  # return type of magic methods
    "RET504",  # unnecessary assigment of return variable
]